name: Pipeline2 Scheduler

on:
  schedule:
    - cron: "0 20 */3 * *" # 3h sáng GMT+7 (20h UTC) mỗi 3 ngày
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create storage directory
        run: mkdir -p src/storage

      - name: Run pipeline2
        run: python src/pipeline2.py
        env:
          COOKIES_CONTENT: ${{ secrets.COOKIES_CONTENT }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
